language: node_js
node_js:
  - 0.10

env:
  global:
  - secure: |-
      TXMriyfSPDxLgoxxAH+g6EtVc+T6FOJBxxR9wONieCr/BsaljlFhmWw2RoyZ698lE6KqJ5g8tJik/Woopqs57xquOZB58w3aVpi/01Z0KYHZMhzUH0/HjrqxBlt/rjR4f/bq/Uz1FvauqfNHwq1jWkb6Pa3AaYAMUP3vSPI/dtc=
  - secure: |-
      NSoYrVLlF0wBVM47JsPSlpvMQovwD6I8oZn0tcWcbbljmlp/iqifQPqPZFokexgRR80Ih5VCAWKRV/DvBj48AkC9yccWglPhDRo8zQzxpVXifhWAepAReyU68yGceHLiW7J5UL0fSyA5If7ezwlMXGfHNh2dq+gzUcZCOCYQkJM=

before_script:
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet -g grunt-cli karma
  - npm install

script: grunt